// * Get Transaction
export const GET_TRANSACTION_REQUEST = 'CartPage/GET_TRANSACTION_REQUEST';
export const GET_TRANSACTION_FAILURE = 'CartPage/GET_TRANSACTION_FAILURE';
export const GET_TRANSACTION_SUCCESS = 'CartPage/GET_TRANSACTION_SUCCESS';

// * Get Shopping Cart;
export const GET_SHOPPING_CART_SUCCESS = 'CartPage/GET_SHOPPING_CART_SUCCESS';
export const GET_SHOPPING_CART_REQUEST = 'CartPage/GET_SHOPPING_CART_REQUEST';
export const GET_SHOPPING_CART_FAILURE = 'CartPage/GET_SHOPPING_CART_FAILURE';
export const GET_COUNT_SHOPPING_CART_SUCCESS = 'CartPage/GET_COUNT_SHOPPING_CART_SUCCESS';
export const GET_COUNT_SHOPPING_CART_REQUEST = 'CartPage/GET_COUNT_SHOPPING_CART_REQUEST';
export const GET_COUNT_SHOPPING_CART_FAILURE = 'CartPage/GET_COUNT_SHOPPING_CART_FAILURE';



// * Create Transaction (Add Cart)
export const ADD_TRANSACTION_REQUEST = 'CartPage/ADD_TRANSACTION_REQUEST';
export const ADD_TRANSACTION_FAILURE = 'CartPage/ADD_TRANSACTION_FAILURE';
export const ADD_TRANSACTION_SUCCESS = 'CartPage/ADD_TRANSACTION_SUCCESS';

// * Create Payment
export const CREATE_PAYMENT_REQUEST = 'CartPage/CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_FAILURE = 'CartPage/CREATE_PAYMENT_FAILURE';
export const CREATE_PAYMENT_SUCCESS = 'CartPage/CREATE_PAYMENT_SUCCESS';

// * Change Amount
export const CHANGE_AMOUNT_REQUEST = 'CartPage/CHANGE_AMOUNT_REQUEST';
export const CHANGE_AMOUNT_FAILURE = 'CartPage/CHANGE_AMOUNT_FAILURE';
export const CHANGE_AMOUNT_SUCCESS = 'CartPage/CHANGE_AMOUNT_SUCCESS';
