export const QUESTIONNAIRE_LIST_DETAIL_REQUEST =
  'Questionnaire/QUESTIONNAIRE_LIST_DETAIL_REQUEST';
export const QUESTIONNAIRE_LIST_DETAIL_SUCCESS =
  'Questionnaire/QUESTIONNAIRE_LIST_DETAIL_SUCCESS';
export const QUESTIONNAIRE_LIST_DETAIL_FAILURE =
  'Questionnaire/QUESTIONNAIRE_LIST_DETAIL_FAILURE';

export const QUESTIONNAIRE_SEND_ANSWER_REQUEST =
  'Questionnaire/QUESTIONNAIRE_SEND_ANSWER_REQUEST';
export const QUESTIONNAIRE_SEND_ANSWER_FAILURE =
  'Questionnaire/QUESTIONNAIRE_SEND_ANSWER_FAILURE';
export const QUESTIONNAIRE_SEND_ANSWER_SUCCESS =
  'Questionnaire/QUESTIONNAIRE_SEND_ANSWER_SUCCESS';
