// * Get Profile
export const ACCOUNT_DETAIL_REQUEST = 'Account/ACCOUNT_DETAIL_REQUEST';
export const ACCOUNT_DETAIL_FAILURE = 'Account/ACCOUNT_DETAIL_FAILURE';
export const ACCOUNT_DETAIL_SUCCESS = 'Account/ACCOUNT_DETAIL_SUCCESS';

// * Update Profile
export const UPDATE_PROFILE_REQUEST = 'Account/UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_FAILURE = 'Account/UPDATE_PROFILE_FAILURE';
export const UPDATE_PROFILE_SUCCESS = 'Account/UPDATE_PROFILE_SUCCESS';
