// * Register
export const CREATE_ACCOUNT_REQUEST = 'CreateAccount/CREATE_ACCOUT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'CreateAccount/CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CreateAccount/CREATE_ACCOUNT_FAILURE';

// * Diagnose Id
export const GET_DIAGNOSE_ID_REQUEST = 'CreateAccount/GET_DIAGNOSE_ID_REQUEST';
export const GET_DIAGNOSE_ID_FAILURE = 'CreateAccount/GET_DIAGNOSE_ID_FAILURE';
export const GET_DIAGNOSE_ID_SUCCESS = 'CreateAccount/GET_DIAGNOSE_ID_SUCCESS';

// * Care Option
export const GET_CARE_OPTION_REQUEST = 'CreateAccount/GET_CARE_OPTION_REQUEST';
export const GET_CARE_OPTION_FAILURE = 'CreateAccount/GET_CARE_OPTION_FAILURE';
export const GET_CARE_OPTION_SUCCESS = 'CreateAccount/GET_CARE_OPTION_SUCCESS';

// * Post Selected Care Option
export const POST_CARE_OPTION_VIDCALL_REQUEST =
  'CreateAccount/POST_CARE_OPTION_VIDCALL_REQUEST';
export const POST_CARE_OPTION_VIDCALL_FAILURE =
  'CreateAccount/POST_CARE_OPTION_VIDCALL_FAILURE';
export const POST_CARE_OPTION_VIDCALL_SUCCESS =
  'CreateAccount/POST_CARE_OPTION_VIDCALL_SUCCESS';

export const POST_CARE_OPTION_PRODUCT_REQUEST =
  'CreateAccount/POST_CARE_OPTION_PRODUCT_REQUEST';
export const POST_CARE_OPTION_PRODUCT_FAILURE =
  'CreateAccount/POST_CARE_OPTION_PRODUCT_FAILURE';
export const POST_CARE_OPTION_PRODUCT_SUCCESS =
  'CreateAccount/POST_CARE_OPTION_PRODUCT_SUCCESS';

// * Shipping
export const POST_USER_SHIPPING_REQUEST =
  'CreateAccount/POST_USER_SHIPPING_REQUEST';
export const POST_USER_SHIPPING_FAILURE =
  'CreateAccount/POST_USER_SHIPPING_FAILURE';
export const POST_USER_SHIPPING_SUCCESS =
  'CreateAccount/POST_USER_SHIPPING_SUCCESS';

// * Create Payment
export const CREATE_PAYMENT_REQUEST = 'CreateAccount/CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_FAILURE = 'CreateAccount/CREATE_PAYMENT_FAILURE';
export const CREATE_PAYMENT_SUCCESS = 'CreateAccount/CREATE_PAYMENT_SUCCESS';

// * Get Profile
export const ACCOUNT_DETAIL_REQUEST = 'Account/ACCOUNT_DETAIL_REQUEST';
export const ACCOUNT_DETAIL_FAILURE = 'Account/ACCOUNT_DETAIL_FAILURE';
export const ACCOUNT_DETAIL_SUCCESS = 'Account/ACCOUNT_DETAIL_SUCCESS';

// * Get Dermatologist
export const GET_DERMATOLOGIST_REQUEST =
  'CreateAccount/GET_DERMATOLOGIST_REQUEST';
export const GET_DERMATOLOGIST_FAILURE =
  'CreateAccount/GET_DERMATOLOGIST_FAILURE';
export const GET_DERMATOLOGIST_SUCCESS =
  'CreateAccount/GET_DERMATOLOGIST_SUCCESS';
