// * Product Detail
export const PRODUCT_DETAIL_FETCH_REQUEST =
  'ProductPage/PRODUCT_DETAIL_FETCH_REQUEST';
export const PRODUCT_DETAIL_FETCH_FAILURE =
  'ProductPage/PRODUCT_DETAIL_FETCH_FAILURE';
export const PRODUCT_DETAIL_FETCH_SUCCESS =
  'ProductPage/PRODUCT_DETAIL_FETCH_SUCCESS';
