// * Product List
export const PRODUCT_LIST_FETCH_REQUEST =
  'ProductPage/PRODUCT_LIST_FETCH_REQUEST';
export const PRODUCT_LIST_FETCH_FAILURE =
  'ProductPage/PRODUCT_LIST_FETCH_FAILURE';
export const PRODUCT_LIST_FETCH_SUCCESS =
  'ProductPage/PRODUCT_LIST_FETCH_SUCCESS';

// * Product Recommended
export const PRODUCT_REC_FETCH_REQUEST =
  'ProductPage/PRODUCT_REC_FETCH_REQUEST';
export const PRODUCT_REC_FETCH_FAILURE =
  'ProductPage/PRODUCT_REC_FETCH_FAILURE';
export const PRODUCT_REC_FETCH_SUCCESS =
  'ProductPage/PRODUCT_REC_FETCH_SUCCESS';

// * Product Detail
export const PRODUCT_DETAIL_FETCH_REQUEST =
  'ProductPage/PRODUCT_DETAIL_FETCH_REQUEST';
export const PRODUCT_DETAIL_FETCH_FAILURE =
  'ProductPage/PRODUCT_DETAIL_FETCH_FAILURE';
export const PRODUCT_DETAIL_FETCH_SUCCESS =
  'ProductPage/PRODUCT_DETAIL_FETCH_SUCCESS';

// * Get Transaction
export const GET_TRANSACTION_REQUEST = 'ProductPage/GET_TRANSACTION_REQUEST';
export const GET_TRANSACTION_FAILURE = 'ProductPage/GET_TRANSACTION_FAILURE';
export const GET_TRANSACTION_SUCCESS = 'ProductPage/GET_TRANSACTION_SUCCESS';

// * Create Transaction (Add Cart)
export const ADD_TRANSACTION_REQUEST = 'ProductPage/ADD_TRANSACTION_REQUEST';
export const ADD_TRANSACTION_FAILURE = 'ProductPage/ADD_TRANSACTION_FAILURE';
export const ADD_TRANSACTION_SUCCESS = 'ProductPage/ADD_TRANSACTION_SUCCESS';

// * User Journey
export const JOURNEY_FETCH_REQUEST = 'LoggedInPage/JOURNEY_FETCH_REQUEST';
export const JOURNEY_FETCH_FAILURE = 'LoggedInPage/JOURNEY_FETCH_FAILURE';
export const JOURNEY_FETCH_SUCCESS = 'LoggedInPage/JOURNEY_FETCH_SUCCESS';
