// * GET USER TESTIMONY
export const LIST_TESTIMONY_FETCH_REQUEST =
  'HomePage/LIST_TESTIMONY_FETCH_REQUEST';
export const LIST_TESTIMONY_FETCH_FAILURE =
  'HomePage/LIST_TESTIMONY_FETCH_FAILURE';
export const LIST_TESTIMONY_FETCH_SUCCESS =
  'HomePage/LIST_TESTIMONY_FETCH_SUCCESS';

// * GET PATIENT TESTIMONY
export const PATIENT_TESTIMONY_FETCH_REQUEST =
  'HomePage/PATIENT_TESTIMONY_FETCH_REQUEST';
export const PATIENT_TESTIMONY_FETCH_FAILURE =
  'HomePage/PATIENT_TESTIMONY_FETCH_FAILURE';
export const PATIENT_TESTIMONY_FETCH_SUCCESS =
  'HomePage/PATIENT_TESTIMONY_FETCH_SUCCESS';

// * GET DOCTOR TESTIMONY
export const DOCTOR_TESTIMONY_FETCH_REQUEST =
  'HomePage/DOCTOR_TESTIMONY_FETCH_REQUEST';
export const DOCTOR_TESTIMONY_FETCH_FAILURE =
  'HomePage/DOCTOR_TESTIMONY_FETCH_FAILURE';
export const DOCTOR_TESTIMONY_FETCH_SUCCESS =
  'HomePage/DOCTOR_TESTIMONY_FETCH_SUCCESS';
