// * User Journey
export const JOURNEY_FETCH_REQUEST = 'LoggedInPage/JOURNEY_FETCH_REQUEST';
export const JOURNEY_FETCH_FAILURE = 'LoggedInPage/JOURNEY_FETCH_FAILURE';
export const JOURNEY_FETCH_SUCCESS = 'LoggedInPage/JOURNEY_FETCH_SUCCESS';

// * Guides
export const GUIDES_FETCH_REQUEST = 'LoggedInPage/GUIDES_FETCH_REQUEST';
export const GUIDES_FETCH_FAILURE = 'LoggedInPage/GUIDES_FETCH_FAILURE';
export const GUIDES_FETCH_SUCCESS = 'LoggedInPage/GUIDES_FETCH_SUCCESS';

// * Product Recommended
export const PRODUCT_REC_FETCH_REQUEST =
  'LoggedInPage/PRODUCT_REC_FETCH_REQUEST';
export const PRODUCT_REC_FETCH_FAILURE =
  'LoggedInPage/PRODUCT_REC_FETCH_FAILURE';
export const PRODUCT_REC_FETCH_SUCCESS =
  'LoggedInPage/PRODUCT_REC_FETCH_SUCCESS';

// * Diagnose
export const DIAGNOSE_FETCH_REQUEST = 'LoggedInPage/DIAGNOSE_FETCH_REQUEST';
export const DIAGNOSE_FETCH_FAILURE = 'LoggedInPage/DIAGNOSE_FETCH_FAILURE';
export const DIAGNOSE_FETCH_SUCCESS = 'LoggedInPage/DIAGNOSE_FETCH_SUCCESS';

// * Treatment Plan Message
export const TREATMENT_MESSAGE_FETCH_REQUEST =
  'LoggedInPage/TREATMENT_MESSAGE_FETCH_REQUEST';
export const TREATMENT_MESSAGE_FETCH_FAILURE =
  'LoggedInPage/TREATMENT_MESSAGE_FETCH_FAILURE';
export const TREATMENT_MESSAGE_FETCH_SUCCESS =
  'LoggedInPage/TREATMENT_MESSAGE_FETCH_SUCCESS';

// * Create Transaction (Add Cart)
export const ADD_TRANSACTION_REQUEST = 'LoggedInPage/ADD_TRANSACTION_REQUEST';
export const ADD_TRANSACTION_FAILURE = 'LoggedInPage/ADD_TRANSACTION_FAILURE';
export const ADD_TRANSACTION_SUCCESS = 'LoggedInPage/ADD_TRANSACTION_SUCCESS';

export const CLEAR_DATA = 'LoggedInPage/CLEAR_DATA';
