// * Get Profile
export const PAYMENT_GATEWAYS_REQUEST = 'Account/PAYMENT_GATEWAYS_REQUEST';
export const PAYMENT_GATEWAYS_FAILURE = 'Account/PAYMENT_GATEWAYS_FAILURE';
export const PAYMENT_GATEWAYS_SUCCESS = 'Account/PAYMENT_GATEWAYS_SUCCESS';
